# Generated by Django 4.0.1 on 2022-02-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docvaultwebsite', '0022_remove_document_details_document_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='document_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=30)),
                ('document_description', models.TextField(default='')),
                ('document_status', models.CharField(max_length=30)),
                ('document_size', models.FloatField()),
                ('document_path', models.CharField(max_length=150)),
                ('document_publish_date_time', models.DateTimeField(auto_now_add=True)),
                ('document_password', models.CharField(max_length=30)),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultuser.document_category')),
            ],
        ),
        migrations.CreateModel(
            name='premium_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=30)),
                ('package_publish_date_time', models.DateTimeField(auto_now_add=True)),
                ('package_status', models.CharField(max_length=30)),
                ('package_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='security_technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_package_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=30)),
                ('package_purchase_date', models.DateTimeField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.user_details')),
                ('premium_package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultuser.premium_package')),
            ],
        ),
        migrations.CreateModel(
            name='user_card_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_month', models.CharField(max_length=30)),
                ('expiry_year', models.CharField(max_length=4)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=30)),
                ('feedback_comment', models.TextField()),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=30)),
                ('enquiry_message', models.TextField()),
                ('enquiry_subject', models.CharField(max_length=50)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='document_privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_status', models.IntegerField()),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultuser.document_details')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.user_details')),
            ],
        ),
        migrations.AddField(
            model_name='document_details',
            name='document_security_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultuser.security_technique'),
        ),
        migrations.AddField(
            model_name='document_details',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.user_details'),
        ),
    ]
