# Generated by Django 4.0 on 2022-02-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_details',
            name='image',
            field=models.ImageField(default='', upload_to='photos'),
        ),
    ]
