# Generated by Django 4.0.2 on 2022-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_details',
            name='document_category',
        ),
        migrations.RemoveField(
            model_name='document_details',
            name='document_path',
        ),
        migrations.AddField(
            model_name='document_details',
            name='document',
            field=models.FileField(default=2, upload_to='document_folder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document_details',
            name='document_type',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='document_category',
        ),
    ]
