# Generated by Django 4.0.2 on 2022-03-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0002_document_details_image'),
        ('docvaultuser', '0002_remove_document_details_document_category_and_more'),
    ]

    operations = [
    ]
