# Generated by Django 4.0.2 on 2022-03-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0003_merge_20220306_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_details',
            name='image',
        ),
        migrations.AlterField(
            model_name='document_details',
            name='document_size',
            field=models.CharField(max_length=50),
        ),
    ]
