# Generated by Django 4.0.2 on 2022-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0004_remove_document_details_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium_package',
            name='package_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='premium_package',
            name='package_duration',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user_package_details',
            name='package_purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
