# Generated by Django 4.0 on 2022-03-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0005_premium_package_package_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_package_details',
            name='package_purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
