# Generated by Django 4.0.2 on 2022-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0006_alter_premium_package_package_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_package_details',
            name='package_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
