# Generated by Django 4.0.2 on 2022-03-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0007_user_package_details_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_package_details',
            name='package_status',
        ),
    ]
