# Generated by Django 4.0.2 on 2022-03-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0008_remove_user_package_details_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='document_publish_date_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_package_details',
            name='package_purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
