# Generated by Django 4.0.2 on 2022-03-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0009_alter_document_details_document_publish_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_details',
            name='document_bin',
            field=models.IntegerField(default=0),
        ),
    ]
