# Generated by Django 4.0 on 2022-03-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0010_document_details_document_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_privilege',
            name='sent_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
