# Generated by Django 4.0 on 2022-03-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0011_document_privilege_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_details',
            name='document_sent',
            field=models.IntegerField(default=0),
        ),
    ]
