# Generated by Django 4.0 on 2022-03-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0012_document_details_document_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_privilege',
            name='sent_by',
        ),
    ]
