# Generated by Django 4.0 on 2022-03-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0013_remove_document_privilege_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_privilege',
            name='sent_to',
            field=models.CharField(default='', max_length=30),
        ),
    ]
