# Generated by Django 4.0.2 on 2022-03-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0006_alter_user_package_details_package_purchase_date'),
        ('docvaultuser', '0014_document_privilege_sent_to'),
    ]

    operations = [
    ]
