# Generated by Django 4.0.2 on 2022-03-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0015_merge_20220321_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_package_details',
            name='package_purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
