# Generated by Django 4.0.2 on 2022-03-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultuser', '0016_alter_user_package_details_package_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='document_password',
            field=models.CharField(max_length=130),
        ),
    ]
