# Generated by Django 4.0.1 on 2022-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
