# Generated by Django 4.0.1 on 2022-02-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0002_alter_user_details_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.city'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='dp',
            field=models.ImageField(default='', upload_to='dp_folder'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='role',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.state'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='status',
            field=models.IntegerField(default=''),
        ),
    ]
