# Generated by Django 4.0.1 on 2022-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0003_alter_user_details_address_alter_user_details_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_card_details',
            name='expiry_month',
            field=models.CharField(max_length=30),
        ),
    ]
