# Generated by Django 4.0.1 on 2022-02-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0004_alter_user_card_details_expiry_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='firstname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='firstname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
