# Generated by Django 4.0.1 on 2022-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0006_alter_user_details_dob_alter_user_details_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='dob',
            field=models.DateField(default='2003-02-04'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='role',
            field=models.IntegerField(default='2'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='status',
            field=models.IntegerField(default='1'),
        ),
    ]
