# Generated by Django 4.0.1 on 2022-02-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0008_alter_user_details_city_alter_user_details_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.city'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='state',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.state'),
        ),
    ]
