# Generated by Django 4.0.1 on 2022-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0010_alter_user_details_city_alter_user_details_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='address',
            field=models.TextField(default='Address'),
        ),
    ]
