# Generated by Django 4.0.1 on 2022-02-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0012_alter_user_details_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='confirm_password',
            field=models.CharField(max_length=30),
        ),
    ]
