# Generated by Django 4.0.1 on 2022-02-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0013_alter_user_details_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
