# Generated by Django 4.0.1 on 2022-02-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0014_alter_user_details_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='confirm_password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
