# Generated by Django 4.0.1 on 2022-02-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0016_alter_user_details_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='confirm_password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='dp',
            field=models.ImageField(default='dp_folder/defaultuser.jpg', upload_to='dp_folder'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
