# Generated by Django 4.0.1 on 2022-02-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0018_alter_user_details_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='dp',
            field=models.ImageField(default='dp_folder/defaultuser.jpg', upload_to='dp_folder'),
        ),
    ]
