# Generated by Django 4.0.1 on 2022-02-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0021_alter_feedback_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_details',
            name='document_category',
        ),
        migrations.RemoveField(
            model_name='document_details',
            name='document_security_technique',
        ),
        migrations.RemoveField(
            model_name='document_details',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='document_privilege',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='document_privilege',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='user_card_details',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='user_package_details',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='user_package_details',
            name='premium_package_id',
        ),
        migrations.DeleteModel(
            name='document_category',
        ),
        migrations.DeleteModel(
            name='document_details',
        ),
        migrations.DeleteModel(
            name='document_privilege',
        ),
        migrations.DeleteModel(
            name='enquiry',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='premium_package',
        ),
        migrations.DeleteModel(
            name='security_technique',
        ),
        migrations.DeleteModel(
            name='user_card_details',
        ),
        migrations.DeleteModel(
            name='user_package_details',
        ),
    ]
