# Generated by Django 4.0.2 on 2022-02-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0022_remove_document_details_document_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.city'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='state',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.CASCADE, to='docvaultwebsite.state'),
        ),
    ]
