# Generated by Django 4.0.2 on 2022-02-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0024_alter_user_details_city_alter_user_details_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.CharField(default='City', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='state',
            field=models.CharField(default='State', max_length=30),
        ),
    ]
