# Generated by Django 4.0 on 2022-03-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0025_alter_user_details_city_alter_user_details_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='package_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
