# Generated by Django 4.0.2 on 2022-03-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0025_alter_user_details_city_alter_user_details_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='dob',
            field=models.DateField(),
        ),
    ]
