# Generated by Django 4.0 on 2022-03-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0026_user_details_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='package_status',
        ),
    ]
