# Generated by Django 4.0.2 on 2022-03-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0026_alter_user_details_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='dob',
            field=models.DateField(default='01-01-2000'),
        ),
    ]
