# Generated by Django 4.0.2 on 2022-03-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0028_alter_user_details_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='confirm_password',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=130),
        ),
    ]
