# Generated by Django 4.0.2 on 2022-03-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0029_alter_user_details_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='confirm_password',
        ),
    ]
