# Generated by Django 4.0.2 on 2022-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0030_remove_user_details_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='confirm_password',
            field=models.CharField(default='', max_length=130),
        ),
    ]
