# Generated by Django 4.0.2 on 2022-03-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docvaultwebsite', '0027_remove_user_details_package_status'),
        ('docvaultwebsite', '0031_user_details_confirm_password'),
    ]

    operations = [
    ]
